### ISSUE TITLE
Empty column values are showing as `null` when in the collapsed menu

### ISSUE THREAD

**Issue by jeffblake** [DataTables/Responsive#105]
My setup is using serverSide. 

The attribute in question is provided in `ticket_fields.id.value` json where id is replaced by the field ID.

In normal view, if the column value is empty, it works as expected: the td cell is blank. However, if the column becomes hidden, the value changes to null, when I expect it to be blank, like in the non-responsive view.

**Comment by DataTables** [comment]
Could you give me a link to a page showing the issue please? [Trying it here](http://live.datatables.net/nabiwami/1/edit) shows an empty string rather than `null` in the responsive row.

**Comment by jeffblake** [comment]
Sorry I can't send a link to one.

The reason that demo works I think is because it's not using a nested key from the server.

**Comment by DataTables** [comment]
I've [updated the example](http://live.datatables.net/nabiwami/2/edit) to use nested data and it still appears to be okay.

**Comment by jeffblake** [comment]
I think I've diagnosed the error better:

Sequence of events
1. $.fn.dataTable.ext.errMode = 'none' . -->> resulted in above silent bug
2. Added Bugsnag error tracking library. I think this re-surfaced the error that was silenced by the setting in step 1. I was getting a bunch of these errors:

<img width="603" alt="screen shot 2018-02-02 at 8 47 17 am" src="https://user-images.githubusercontent.com/620564/35744643-b7183b90-07f5-11e8-9b33-96aa2571e1bc.png">

3. Then I added the `defaultContent` property, and everything is now working.

**Comment by DataTables** [comment]
Yes - DataTables doesn't just treat `null` or `undefined` as an empty string intentionally. It might be that you want to set it to be _"No data"_ or similar (which `null` often means rather than an empty string) - so DataTables forces you to be explicit about it.

Currently no - there isn't a way to selectively set errorMode for specific errors. You _could_ use it as a function and then do the selection yourself.

Going to close this as DataTables appears to be working as designed.
