### ISSUE TITLE
Can't Expand When Icon in Separate Column

### ISSUE THREAD

**Issue by ComputerTinker** [DataTables/Responsive#16]
If I create a responsive table with:

```javascript
    "responsive": true
```

everything works fine, however, if I replace that line with:

```javascript
    "responsive": {
      "details": {
        "type": "column"
      }
    }
```

and add the appropriate columns to the table, then I can see the icon being displayed in the separate column, however clicking the icon does not result in the table expanding to show the hidden columns.  

Here is a live example of the issue:
http://jsfiddle.net/ng9ku8y9/

Any help appreciated.  Thank you!

**Comment by cdaringe** [comment]
@ComputerTinker, would you be willing to post/edit a fiddle of your workaround?  I tried editing your fiddle to match the description and it was still being stubborn

**Comment by ComputerTinker** [comment]
Thanks for following up. I'm totally swamped at the moment but I will try to get you that fiddle soon.

**Comment by DataTables** [comment]
The issue here is that Responsive will assume a target column of index 0 for the Responsive control. In this case the target column for the control is actually index 2, so we need to tell Responsive that fact: http://jsfiddle.net/ng9ku8y9/17/ .

I think this could probably be improved, so Responsive detected the `control` class, but for now it works, so doing to close this issue (heading for a year later... sorry!).
