### ISSUE TITLE
Missing plain css file

### ISSUE THREAD

**Issue by amirmohsen** [DataTables/Responsive#75]
This package is missing a plain css file. I am loading this extension via bower and only getting the scss files which are no good for dist purposes. Could you please include a plain css file as part of this package so it can be easily "plugged" into any system?

As a side note, most packages include a src and a dist folder to cater to different needs. It would be good to have a similar thing here.

**Comment by DataTables** [comment]
Hi,

This was raised in #44 and #45. A search for "npm", "bower" or "css" would find those issues.

Because DataTables and its extensions support multiple different styling frameworks a simple `dist` directory isn't really suitable for them to be used with package managers (it is possible to use NPM with specific files, but its not trivial and not how everyone likes to work). Instead distribution repos are available. Information about this is available in:

* [The DataTables installation manual](http://datatables.net/manual/installation)]
* The NPM and Bower download pages - [linked from the main DataTables download page](//datatables.net/download)
* I've just added it to the readme for this repo in 97dc8158ba266d4c44b1d103a7a0a68b735e7530. I thought have done that before.

**Comment by amirmohsen** [comment]
Thanks. That clarifies it. To be honest, the data tables website is a bit old-fashioned and it's hard to find information in there.

**Comment by DataTables** [comment]
I'm open to suggestions on how to improve it.
